import { createFileRoute } from "@tanstack/react-router";
import { Panel, SectionLabel, SiteFooter, SiteHeader } from "@/components/verimedia/Chrome";
import { VerdictBands } from "@/components/verimedia/RiskScore";
import { NOMINAL_WEIGHTS, SOURCE_LABELS } from "@/lib/verimedia/scoring";
import { STAGES } from "@/lib/verimedia/pipeline";

export const Route = createFileRoute("/method")({
  head: () => ({
    meta: [
      { title: "Method & scoring — VeriMedia AI" },
      {
        name: "description",
        content:
          "How VeriMedia AI scores media: four weighted components, deterministic aggregation, renormalisation for unavailable stages, and what the tool deliberately cannot claim.",
      },
      { property: "og:title", content: "Method & scoring — VeriMedia AI" },
      { property: "og:description", content: "Deterministic weighted scoring, explained end to end." },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: MethodPage,
});

const CANNOT = [
  "It cannot prove that a file was generated by a specific model or tool.",
  "It cannot perform reverse image search unless search grounding is configured, and it never invents matches.",
  "It cannot run ffmpeg/ffprobe frame-level codec forensics in this environment, so deep video analysis is limited to browser-decoded frames.",
  "It cannot treat missing EXIF as evidence of AI generation — social platforms strip metadata from almost everything.",
  "It cannot replace a human verification workflow, provenance checks (C2PA), or contacting the original source.",
];

function MethodPage() {
  return (
    <div className="min-h-screen">
      <SiteHeader />
      <main className="px-6 md:px-10">
        <SectionLabel>Method / How the score is produced</SectionLabel>
        <h1 className="headline text-[clamp(2rem,6vw,4.5rem)]">
          Deterministic. <span className="text-brand">Auditable.</span>
        </h1>

        <div className="mt-8 grid gap-5 lg:grid-cols-2">
          <Panel className="p-6">
            <p className="label-mono">Seven stages</p>
            <ol className="mt-3 space-y-2">
              {STAGES.map((s, i) => (
                <li key={s} className="flex gap-3 text-sm">
                  <span className="font-mono text-[11px] text-signal">{String(i + 1).padStart(2, "0")}</span>
                  <span className="text-dim">
                    <span className="font-display font-bold uppercase tracking-wide text-foreground">{s}</span> —{" "}
                    {stageCopy[s]}
                  </span>
                </li>
              ))}
            </ol>
          </Panel>

          <div className="space-y-5">
            <Panel className="p-6">
              <p className="label-mono">Nominal weights</p>
              <div className="mt-3 space-y-3">
                {(Object.keys(NOMINAL_WEIGHTS) as Array<keyof typeof NOMINAL_WEIGHTS>).map((k) => (
                  <div key={k}>
                    <div className="flex justify-between font-mono text-[11px] uppercase tracking-wide">
                      <span className="text-dim">{SOURCE_LABELS[k]}</span>
                      <span className="text-foreground">{Math.round(NOMINAL_WEIGHTS[k] * 100)}%</span>
                    </div>
                    <div className="mt-1 h-1.5 bg-line">
                      <div className="h-full bg-brand" style={{ width: `${NOMINAL_WEIGHTS[k] * 100}%` }} />
                    </div>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-xs leading-relaxed text-dim">
                If a component cannot run, its weight is removed and the remaining weights are renormalised. An
                unavailable stage never counts as a vote for authenticity, and it never counts as a vote against it.
              </p>
            </Panel>
            <Panel className="p-6">
              <p className="label-mono">Verdict bands</p>
              <div className="mt-3">
                <VerdictBands />
              </div>
            </Panel>
          </div>
        </div>

        <section className="mt-14">
          <SectionLabel tone="signal">What this tool cannot do</SectionLabel>
          <Panel dashed className="p-6">
            <ul className="space-y-2 text-sm leading-relaxed text-dim">
              {CANNOT.map((c) => (
                <li key={c}>· {c}</li>
              ))}
            </ul>
          </Panel>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}

const stageCopy: Record<string, string> = {
  Validate: "magic bytes are read from the file head; the browser-declared MIME type is never trusted.",
  Hash: "a SHA-256 digest is computed in-browser so the exact bytes analysed can be cited later.",
  Metadata: "EXIF, ID3, RIFF and container boxes are parsed from the real bytes, with no inference from absence.",
  Forensics: "measurable properties — dimensions, compression, levels, duration, geometry — are recorded as evidence.",
  Gemini: "an optional semantic pass returns observations and interpretations; it has no authority over the score.",
  Web: "optional search grounding for corroborating context. Unavailable unless configured.",
  Score: "component risks are combined with fixed weights into a 0–100 score and a verdict band.",
};
